package main
func ast_to_asm_program(program * Program) string {
	asm := "this is an assembly code generated by minc compiler ...\n"
	panic("YOU MUST IMPLEMENT go/minc/minc_cogen.go:ast_to_asm_program")
    // 再帰で書くのは明らか, ということはasm += ast_to_asm_program(program)のような形が頻発するはず。
    // astの左辺compile, astの右辺コンパイルという順にやって行った方がよさそう。
	return asm
}
